pub trait IamClient {
    // TODO result or more sofisticated response with error?
    fn systemIdentityCreate(&self, req: SystemIdentityRequest) -> SystemIdentityResponse;
}

// Ideally this should be autogenerated from a Protobuf definition provided by the IAM API
pub struct SystemIdentityResponse {
    pub client_id: String,
    pub client_secret: Option<String>,
}

pub struct SystemIdentityRequest {
    pub name: String,
    pub org_id: String,
    pub pub_key: Option<String>,
}
