name: 📞 Build container images
on:
  workflow_call:
    inputs:
      image-tag:
        description: 'Image tag'
        type: string
        required: true
      push:
        description: 'Push image'
        type: boolean
        required: true
permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Build/Push images
    env:
      DOCKER_IMAGE_NAME_AUTH: newrelic/agent-control-system-identity-registration
      DOCKER_PLATFORMS: "linux/amd64,linux/arm64"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Obtain Rust version from project
        run: |
          RUST_VERSION=$(grep "rust-version" Cargo.toml | cut -d "=" -f2 | tr -d "[:space:]")
          echo "RUST_VERSION=${RUST_VERSION}" >> $GITHUB_ENV

      - name: Install Rust ${{ env.RUST_VERSION }}
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: >-
            aarch64-unknown-linux-musl,
            x86_64-unknown-linux-musl

      - name: Install Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2

      - uses: taiki-e/install-action@288e746965032cfcc232e09af2daf5f23c14d780 # v2.86.1
        with:
          tool: cargo-zigbuild@0.20.1

      - name: Build newrelic auth cli
        run: |
          cargo zigbuild --release --target "aarch64-unknown-linux-musl" 
          cargo zigbuild --release --target "x86_64-unknown-linux-musl"  
          cp ./target/aarch64-unknown-linux-musl/release/newrelic-auth-cli ./target/newrelic-auth-cli-arm64
          cp ./target/x86_64-unknown-linux-musl/release/newrelic-auth-cli ./target/newrelic-auth-cli-amd64

      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ secrets.OHAI_DOCKER_HUB_ID }}
          password: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}

      - name: Build and push images
        if: ${{ inputs.push }}
        run: |
          docker buildx build \
            --push \
            --platform=$DOCKER_PLATFORMS \
            -t $DOCKER_IMAGE_NAME_AUTH:${{ inputs.image-tag }} \
            --attest type=provenance,mode=max \
            --attest type=sbom \
            .

      - name: Build images
        if: ${{ ! inputs.push }}
        run: |
          docker buildx build \
            --platform=$DOCKER_PLATFORMS \
            -t $DOCKER_IMAGE_NAME_AUTH:${{ inputs.image-tag }} \
            --attest type=provenance,mode=max \
            --attest type=sbom \
            .
