name: ⏯️ Generate pre-release PR

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prerelease:
    uses: newrelic/newrelic-agent-control/.github/workflows/shared_create_prerelease_pr.yml@e40923bdf943ee2a4b1c04b11b308451fa0b4790 # main
    secrets:
      app_id: ${{ secrets.AGENT_CONTROL_APP_ID }}
      app_private_key: ${{ secrets.AGENT_CONTROL_APP_PKEY }}

