name: validates changelog

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

permissions:
  contents: read
  pull-requests: read

jobs:
  check-changelog:
    uses: newrelic/newrelic-agent-control/.github/workflows/shared_check_changelog.yml@b7de4df398ab2d6ced86b9144f1b4d48b9845247 # main
