name: validates changelog

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

permissions:
  contents: read
  pull-requests: read

jobs:
  check-changelog:
    uses: newrelic/newrelic-agent-control/.github/workflows/shared_check_changelog.yml@9e641ddf22dbc62e3c1d02ddb3ef77f491207715 # main
