name: Release
on:
  release:
    types:
      - released
    tags:
      - '*'
permissions:
  contents: read
jobs:
  push-container-tags:
    runs-on: ubuntu-latest
    name: Push container release tags
    env:
      DOCKER_IMAGE_NAME_AUTH: newrelic/agent-control-system-identity-registration
    steps:
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4

      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          username: ${{ secrets.OHAI_DOCKER_HUB_ID }}
          password: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}

      - name: Push release tags
        run: |
          docker buildx imagetools create \
            -t $DOCKER_IMAGE_NAME_AUTH:${{ github.event.release.tag_name }} \
            -t $DOCKER_IMAGE_NAME_AUTH:latest \
            $DOCKER_IMAGE_NAME_AUTH:${{ github.event.release.tag_name }}-rc


  notify-failure:
    if: ${{ failure() }}
    needs: [ push-container-tags ]
    runs-on: ubuntu-latest
    steps:
    - name: Notify failure via Slack
      uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
      with:
        payload: |
          {
            "text": ":warning: [Release failed for `newrelic-auth-rs`] @hero check <${{ env.GITHUB_JOB_URL }}>"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.AC_SLACK_WEBHOOK }}
        GITHUB_JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
