name: Release
on:
  release:
    types:
      - released
    tags:
      - '*'
permissions:
  contents: read
jobs:
  push-container-tags:
    runs-on: ubuntu-latest
    name: Push container release tags
    env:
      DOCKER_IMAGE_NAME_AUTH: newrelic/agent-control-system-identity-registration
    steps:
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ secrets.OHAI_DOCKER_HUB_ID }}
          password: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}

      - name: Push release tags
        run: |
          docker buildx imagetools create \
            -t $DOCKER_IMAGE_NAME_AUTH:${{ github.event.release.tag_name }} \
            -t $DOCKER_IMAGE_NAME_AUTH:latest \
            $DOCKER_IMAGE_NAME_AUTH:${{ github.event.release.tag_name }}-rc


  notify-failure:
    if: ${{ failure() }}
    needs: [ push-container-tags ]
    runs-on: ubuntu-latest
    steps:
    - name: Notify failure via Slack
      uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
      with:
        payload: |
          {
            "text": ":warning: [Release failed for `newrelic-auth-rs`] @hero check <${{ env.GITHUB_JOB_URL }}>"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.AC_SLACK_WEBHOOK }}
        GITHUB_JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
